### ISSUE TITLE
flickering / button size

### ISSUE THREAD

**Issue by D1ck3sb** [oddbear/TouchPortal.Plugin.AudioMonitor#17]
The audio bargraph (v2 / android 7.0) has been flickering for some time and the display is always 1x1, regardless of which button size has been selected.

With best regards

D1ck3s B

**Comment by oddbear** [comment]
Hi, for the flickering it can be that the image has to high resolution (`Width`, `Height`), or the `UpdateInterval` is set to low. There is a `Debug` options that shows a counter (can be changed from `false` to `true`), and if this skips frames, or is displayed in the wrong order, then the plugin is sending more data than the app/network can handle.

For the 1x1, I would try to click the refresh button in the App (top right corner).
This can also be that the configuration file has an issue in it, and therefore the plugin ignores the changes. If nothing happens at all, then this is most likely the case. You can try using the [JSON Schema Validator](https://www.jsonschemavalidator.net/s/9341jfJh) and copy in your own configuration (or share it here).

If this is something that worked better for you before, I am really interested in when it started to change. The Touch Portal team is testing out sliders and similar at this time, and this might have changed something in the App.

I will also try to test this out myself and see if I find something.

**Comment by oddbear** [comment]
@D1ck3sb when I re-read your issue her, it might be that you have not changed the appsettings file? In that case my comment might not give any sense.

It works on my device, but the default is a squared image.
After you have changed the configuration file, you will need to refresh the page on Android, but this should only be the first time.

Configuration file can be found at: `C:\Users\oddbj\AppData\Roaming\TouchPortal\plugins\TouchPortal.Plugin.AudioMonitor\appsettings.json` just replace oddbj with your windows username.

**Comment by D1ck3sb** [comment]
Thank you for your answer and 
apologize for not getting in touch first. was unfortunately too busy. 

The error was, I had incorrectly interpreted the update interval 
( total failure of logical thinking :-) )
and therefore set it incorrectly. 
After I changed it, the button size could also be changed again.

**Comment by oddbear** [comment]
Great. Good that it worked out in the end. :)

It might not be the most intuitive explanation from my side, so I might create a video guide or something for future reference.

Closing the issue as it is solved.
