### ISSUE TITLE
Graphs stop updating when computer wakes from sleep or when the audio device gets disconnected and reconnected.

### ISSUE THREAD

**Issue by mtchetch** [oddbear/TouchPortal.Plugin.AudioMonitor#18]
This is fixed by restarting touch portal but would like it to automatically redetect audio devices and just work.

Steps to reproduce:

Monitor a USB audio device like a USB mic or a virtual Mic provided by RTX voice or similar program
Disconnect mic from USB or restart RTX Voice software
Graph stops updating until touch portal is restarted

**Comment by oddbear** [comment]
Interesting, I will look into it, but it might not be before earliest at Sunday.
Thanks for reporting.

**Comment by oddbear** [comment]
Hi again. Sorry it took a while.
I think I was able to reproduce, could you try out the update at: https://github.com/oddbear/TouchPortal.Plugin.AudioMonitor/releases/tag/v2-build-007

**Comment by mtchetch** [comment]
Thanks for letting me know. I will test out your changes and come back to
you.

-Mihail

**Comment by mtchetch** [comment]
Been testing this out for a few days and sleep / wakeup as well as audio device disconnect->reconnect does not stop the graphs from updating.

I think you solved the issue. Good job!
